name: "German_Spark"
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg:
  provider:
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  flutter_tts: ^3.5.3
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  in_app_review:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/stories.json
    - assets/json/podcast.json
    - assets/json/vocabulary.json
    - assets/json/germanbasics.json
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

